### 
GET http://localhost:5144/

### Cadastrar novo contato 
POST http://localhost:5144/api/contatos/cadastrar
Content-Type: application/json

{
  "nome": "Manoel Gomes",
  "email": "manoel@canetaazul.com",
  "celular": "11987654321"
}

### Listar contatos
GET http://localhost:5144/api/contatos/listar

### Buscar contato 
GET http://localhost:5144/api/contatos/buscar/1

### Atualizar contato 
PUT http://localhost:5144/api/contatos/alterar/1
Content-Type: application/json

{
  "nome": "Manoel Gomes aaa",
  "email": "manoel@canetaazul.com",
  "celular": "11987654321"
}

### Deletar um contato por ID (DELETE /api/contatos/deletar/{id})
DELETE http://localhost:5144/api/contatos/deletar/1
