### 
GET http://localhost:5144/


### Cadastrar usuario
POST http://localhost:5144/api/usuarios/cadastrar
Content-Type: application/json

{
  "nome": "Leonardo Heredia",
  "email": "leoTeste@gmail.com",
  "senha": "abc123"
}

### Listar usuarios
GET http://localhost:5144/api/usuarios/listar

### Buscar usuario 
GET http://localhost:5144/api/usuarios/buscar/leoTeste@gmail.com

### Atualizar usuario 
PUT http://localhost:5144/api/usuarios/alterar/leoTeste@yahoo.com/abc123
Content-Type: application/json

{
  "nome": "Leonardo Heredia",
  "email": "leoTeste@gmail.com",
  "senha": "abc123"
}

### Deletar usuario 
DELETE http://localhost:5144/api/usuarios/deletar/leoTeste@gmail.com/abc123

### Cadastrar novo contato 
POST http://localhost:5144/api/contatos/cadastrar/leoTeste@gmail.com/abc123
Content-Type: application/json

{
    "nome": "Eduardo",
    "email": "Eduardo@gmail.com",
    "celular": "11987654322",
    "estado": "SP",
    "cidade": "São Paulo",
    "bairro": "Centro",
    "rua": "Rua das Flores",
    "numero": 123
}


### Listar contatos
GET http://localhost:5144/api/contatos/listar
Content-Type: application/json

{
  "nome": "Leonardo Heredia",
  "email": "leoTeste@gmail.com",
  "senha": "abc123"
}


### Buscar contato 
GET http://localhost:5144/api/contatos/buscar/11987654322
Content-Type: application/json

{
  "nome": "Leonardo Heredia",
  "email": "leoTeste@gmail.com",
  "senha": "abc123"
}

### Atualizar contato 
PUT http://localhost:5144/api/contatos/alterar/leoTeste@gmail.com/abc123/11987654322
Content-Type: application/json

{
    "nome": "Eduardo",
    "email": "Eduardo@Gmail.com",
    "celular": "11987654321",
    "endereco": "Rua Professor Pedro Viriato Parigot de Souza 5300"
}

### Deletar contato 
DELETE http://localhost:5144/api/contatos/deletar/11987654321
Content-Type: application/json

{
  "nome": "Leonardo Heredia",
  "email": "leoTeste@gmail.com",
  "senha": "abc123"
}

